version: '3'

services:
  web:
    build: ./flask
    command: gunicorn -w 4 app:app
    volumes:
      - ./flask/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: kartoza/postgis:9.5-2.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wajeeh-machine
      - POSTGRES_PASSWORD=Waje3e3h
      - POSTGRES_DB=trackcorona
      # - ALLOW_IP_RANGE=0.0.0.0
    ports:
      # - "5432:5432"
      # - "25432:25432"
      - "25432:5432"
  # postgis:
  #   image: ./postgis

volumes:
  postgres_data:




# version: '3'

# services:
#   web:
#     build: ./flask
#     command: python app.py
#     volumes:
#       - ./flask/:/usr/src/app/
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#   db:
#     image: postgres:9.5
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=wajeeh-machine
#       - POSTGRES_PASSWORD=Waje3e3h
#       - POSTGRES_DB=trackcorona
#       - ALLOW_IP_RANGE=0.0.0.0
#     ports:
#       # - "5432:5432"
#     - "25432:25432"
#   postgis:
#     image: ./postgis

# volumes:
#   postgres_data:

