version: '3.7'

services:
  web:
    hostname: web_flask
    restart: always
    build: ./flask
    # command: python app.py -h 0.0.0.0
    command: gunicorn -w 1 app:app
    # command: gunicorn --bind 0.0.0.0:8000 -w 4 app:app
    volumes:
      - ./flask/:/usr/src/app/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - db:db
  db:
    image: kartoza/postgis:9.5-2.2
    restart: always
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wajeeh-machine
      - POSTGRES_PASSWORD=Waje3e3h
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_PASS=Waje3e3h
      - POSTGRES_DB=trackcorona
      # - POSTGRES_DBNAME=trackcorona
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - "5432"
    ports:
      # - "5432:5432"
      # - "db:5432:5432"
      # - "25432:25432"
      # - "db:25432:5432"
      - "25432:5432"
  # nginx:
  #   build: ./nginx
  #   ports:
  #     -1337:80
  #   depends_on:
  #     - web
  # postgis:
  #   image: ./postgis

volumes:
  postgres_data:




# version: '3'

# services:
#   web:
#     build: ./flask
#     command: python app.py
#     volumes:
#       - ./flask/:/usr/src/app/
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#   db:
#     image: postgres:9.5
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=wajeeh-machine
#       - POSTGRES_PASSWORD=Waje3e3h
#       - POSTGRES_DB=trackcorona
#       - ALLOW_IP_RANGE=0.0.0.0
#     ports:
#       # - "5432:5432"
#     - "25432:25432"
#   postgis:
#     image: ./postgis

# volumes:
#   postgres_data:

